#application-c3p0.yml
#配置c3p0的数据池
#配置数据库名
c3p0:
  jdbcUrl: jdbc:mysql://127.0.0.1:3306/1702a?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
  #配置username
  user: root
  #配置password
  password: root
  #配置driver
  driverClass: com.mysql.jdbc.Driver
  #配置最小连接池数据
  minPoolSize: 50
  #配置最大连接数
  maxPoolSize: 50
  #最大空闲时间
  maxIdleTime: 1800000
  #当连接池中的连接耗尽的时候c3p0一次同时获取的连接数,每次增加3个连接
  acquireIncrement: 3
  #最大sql语句
  maxStatements: 1000
  #初始化连接池数
  initialPoolSize: 3
  idleConnectionTestPeriod: 60
  acquireRetryAttempts: 30
  acquireRetryDelay: 1000
  breakAfterAcquireFailure: false
  testConnectionOnCheckout: false
